spring.application.name=JobQueues
spring.threads.virtual.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379

app.queue.stream-name=jobs:stream
app.queue.group-name=jobs:group
app.queue.consumer-name=worker-0
